### ISSUE TITLE
why conj?

### ISSUE THREAD

**Issue by mxs-self** [Abdelrahman-Taha/LIS-DeepLearning#1]
Thank you very much for sharing the code! Would you mind answering a question?
WHY conj?
![conj](https://user-images.githubusercontent.com/24434618/61841475-7b305200-aec7-11e9-99be-5bdebf818da1.jpg)

**Comment by DeepMIMO** [comment]
Since we use the same DeepMIMO function to construct H_t and H_r, we need to take the conjugate of the output of that function and consider it as H_r to account for the direction of propagation. 
(Output DeepMIMO channels are considered in the Uplink direction.)

**Comment by Abdelrahman-Taha** [comment]
Since we use the same DeepMIMO function to construct H_t and H_r, we need to take the conjugate of the output of that function and consider it as H_r to account for the direction of propagation.
(Output DeepMIMO channels are considered in the Uplink direction.)
